name=Illumicro
version=1.0.0
author=EDrTech
maintainer=EDrTech
sentence=A library for controlling the IS31FL3741A LED driver with a 13x9 RGB matrix.
paragraph=Supports PWM, scaling, current control, open/short detection, de-ghosting, interrupts, and buffered display with breathing effects.
category=Display
url=https://www.rudectech.com
architectures=*
depends=Wire
